---
- name: Homework1
  hosts: myhost
  gather_facts: no
  tasks:
    - shell: echo Begin homework 1
    - shell: echo OK

- name: download file
  hosts: myhost
  become: true
  gather_facts: no
  roles:
    - role: download_file

- name: creating user
  hosts: myhost
  gather_facts: no
  roles:
    - role: create_user


- name: Creating JSON
  hosts: myhost
  gather_facts: no
  roles:
    - role: create_json_file

